/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gouv (void)
{
  GtkWidget *gouv;
  GtkWidget *fixed3;
  GtkWidget *image11;
  GtkWidget *button_ajtouv;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image13;
  GtkWidget *label12;
  GtkWidget *button_mdfouv;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image14;
  GtkWidget *label13;
  GtkWidget *button_suppouv;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image15;
  GtkWidget *label14;
  GtkWidget *button_affouv;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image12;
  GtkWidget *label11;
  GtkWidget *button_retouv;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image16;
  GtkWidget *label15;
  GtkWidget *button_rechouv;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image17;
  GtkWidget *label16;
  GtkWidget *button_mbabs;
  GtkWidget *alignment81;
  GtkWidget *hbox81;
  GtkWidget *image108;
  GtkWidget *label196;
  GtkWidget *label_mblouv;
  GtkWidget *scrolledwindow_louv;
  GtkWidget *viewport1;
  GtkWidget *fixed28;
  GtkWidget *treeview_louv;
  GtkWidget *button_qgouv;
  GtkWidget *alignment87;
  GtkWidget *hbox87;
  GtkWidget *image114;
  GtkWidget *label212;

  gouv = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gouv, 620, 430);
  gtk_window_set_title (GTK_WINDOW (gouv), _("Gestion des ouvriers"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (gouv), fixed3);

  image11 = create_pixmap (gouv, "crop-farmer.png");
  gtk_widget_show (image11);
  gtk_fixed_put (GTK_FIXED (fixed3), image11, 0, 0);
  gtk_widget_set_size_request (image11, 620, 430);

  button_ajtouv = gtk_button_new ();
  gtk_widget_show (button_ajtouv);
  gtk_fixed_put (GTK_FIXED (fixed3), button_ajtouv, 168, 400);
  gtk_widget_set_size_request (button_ajtouv, 105, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_ajtouv), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image13 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox10), image13, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("<span><b>ajouter</b></span>"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox10), label12, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);

  button_mdfouv = gtk_button_new ();
  gtk_widget_show (button_mdfouv);
  gtk_fixed_put (GTK_FIXED (fixed3), button_mdfouv, 328, 400);
  gtk_widget_set_size_request (button_mdfouv, 105, 29);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_mdfouv), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image14 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox11), image14, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("<span><b>modifier</b></span>"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox11), label13, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  button_suppouv = gtk_button_new ();
  gtk_widget_show (button_suppouv);
  gtk_fixed_put (GTK_FIXED (fixed3), button_suppouv, 488, 400);
  gtk_widget_set_size_request (button_suppouv, 105, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button_suppouv), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image15 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox12), image15, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("<span><b>supprimer</b></span>"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox12), label14, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  button_affouv = gtk_button_new ();
  gtk_widget_show (button_affouv);
  gtk_fixed_put (GTK_FIXED (fixed3), button_affouv, 8, 400);
  gtk_widget_set_size_request (button_affouv, 105, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_affouv), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image12 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox9), image12, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("<span><b>afficher</b></span>"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox9), label11, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  button_retouv = gtk_button_new ();
  gtk_widget_show (button_retouv);
  gtk_fixed_put (GTK_FIXED (fixed3), button_retouv, 445, 0);
  gtk_widget_set_size_request (button_retouv, 85, 29);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button_retouv), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image16 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox13), image16, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("<span><b>retour</b></span>"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox13), label15, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  button_rechouv = gtk_button_new ();
  gtk_widget_show (button_rechouv);
  gtk_fixed_put (GTK_FIXED (fixed3), button_rechouv, 440, 50);
  gtk_widget_set_size_request (button_rechouv, 105, 29);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_rechouv), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image17 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox14), image17, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("<span><b>rechercher</b></span>"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox14), label16, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  button_mbabs = gtk_button_new ();
  gtk_widget_show (button_mbabs);
  gtk_fixed_put (GTK_FIXED (fixed3), button_mbabs, 440, 88);
  gtk_widget_set_size_request (button_mbabs, 105, 29);

  alignment81 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment81);
  gtk_container_add (GTK_CONTAINER (button_mbabs), alignment81);

  hbox81 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox81);
  gtk_container_add (GTK_CONTAINER (alignment81), hbox81);

  image108 = gtk_image_new_from_stock ("gtk-properties", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image108);
  gtk_box_pack_start (GTK_BOX (hbox81), image108, FALSE, FALSE, 0);

  label196 = gtk_label_new_with_mnemonic (_("<span><b>absentisme</b></span>"));
  gtk_widget_show (label196);
  gtk_box_pack_start (GTK_BOX (hbox81), label196, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label196), TRUE);

  label_mblouv = gtk_label_new (_("<span foreground=\"black\" ><b>Liste des Ouvriers :</b></span>"));
  gtk_widget_show (label_mblouv);
  gtk_fixed_put (GTK_FIXED (fixed3), label_mblouv, 96, 88);
  gtk_widget_set_size_request (label_mblouv, 176, 41);
  gtk_label_set_use_markup (GTK_LABEL (label_mblouv), TRUE);

  scrolledwindow_louv = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow_louv);
  gtk_fixed_put (GTK_FIXED (fixed3), scrolledwindow_louv, 0, 136);
  gtk_widget_set_size_request (scrolledwindow_louv, 620, 230);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow_louv), viewport1);

  fixed28 = gtk_fixed_new ();
  gtk_widget_show (fixed28);
  gtk_container_add (GTK_CONTAINER (viewport1), fixed28);

  treeview_louv = gtk_tree_view_new ();
  gtk_widget_show (treeview_louv);
  gtk_fixed_put (GTK_FIXED (fixed28), treeview_louv, 0, 0);
  gtk_widget_set_size_request (treeview_louv, 700, 1000);

  button_qgouv = gtk_button_new ();
  gtk_widget_show (button_qgouv);
  gtk_fixed_put (GTK_FIXED (fixed3), button_qgouv, 535, 0);
  gtk_widget_set_size_request (button_qgouv, 85, 29);

  alignment87 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment87);
  gtk_container_add (GTK_CONTAINER (button_qgouv), alignment87);

  hbox87 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox87);
  gtk_container_add (GTK_CONTAINER (alignment87), hbox87);

  image114 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image114);
  gtk_box_pack_start (GTK_BOX (hbox87), image114, FALSE, FALSE, 0);

  label212 = gtk_label_new_with_mnemonic (_("<span><b>quitter</b></span>"));
  gtk_widget_show (label212);
  gtk_box_pack_start (GTK_BOX (hbox87), label212, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label212), TRUE);

  g_signal_connect ((gpointer) button_ajtouv, "clicked",
                    G_CALLBACK (on_button_ajtouv_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mdfouv, "clicked",
                    G_CALLBACK (on_button_mdfouv_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_suppouv, "clicked",
                    G_CALLBACK (on_button_suppouv_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_affouv, "clicked",
                    G_CALLBACK (on_button_affouv_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retouv, "clicked",
                    G_CALLBACK (on_button_retouv_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_rechouv, "clicked",
                    G_CALLBACK (on_button_rechouv_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mbabs, "clicked",
                    G_CALLBACK (on_button_mbabs_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_louv, "row_activated",
                    G_CALLBACK (on_treeview_louv_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_qgouv, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gouv, gouv, "gouv");
  GLADE_HOOKUP_OBJECT (gouv, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (gouv, image11, "image11");
  GLADE_HOOKUP_OBJECT (gouv, button_ajtouv, "button_ajtouv");
  GLADE_HOOKUP_OBJECT (gouv, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (gouv, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (gouv, image13, "image13");
  GLADE_HOOKUP_OBJECT (gouv, label12, "label12");
  GLADE_HOOKUP_OBJECT (gouv, button_mdfouv, "button_mdfouv");
  GLADE_HOOKUP_OBJECT (gouv, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (gouv, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (gouv, image14, "image14");
  GLADE_HOOKUP_OBJECT (gouv, label13, "label13");
  GLADE_HOOKUP_OBJECT (gouv, button_suppouv, "button_suppouv");
  GLADE_HOOKUP_OBJECT (gouv, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (gouv, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (gouv, image15, "image15");
  GLADE_HOOKUP_OBJECT (gouv, label14, "label14");
  GLADE_HOOKUP_OBJECT (gouv, button_affouv, "button_affouv");
  GLADE_HOOKUP_OBJECT (gouv, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (gouv, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (gouv, image12, "image12");
  GLADE_HOOKUP_OBJECT (gouv, label11, "label11");
  GLADE_HOOKUP_OBJECT (gouv, button_retouv, "button_retouv");
  GLADE_HOOKUP_OBJECT (gouv, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (gouv, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (gouv, image16, "image16");
  GLADE_HOOKUP_OBJECT (gouv, label15, "label15");
  GLADE_HOOKUP_OBJECT (gouv, button_rechouv, "button_rechouv");
  GLADE_HOOKUP_OBJECT (gouv, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (gouv, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (gouv, image17, "image17");
  GLADE_HOOKUP_OBJECT (gouv, label16, "label16");
  GLADE_HOOKUP_OBJECT (gouv, button_mbabs, "button_mbabs");
  GLADE_HOOKUP_OBJECT (gouv, alignment81, "alignment81");
  GLADE_HOOKUP_OBJECT (gouv, hbox81, "hbox81");
  GLADE_HOOKUP_OBJECT (gouv, image108, "image108");
  GLADE_HOOKUP_OBJECT (gouv, label196, "label196");
  GLADE_HOOKUP_OBJECT (gouv, label_mblouv, "label_mblouv");
  GLADE_HOOKUP_OBJECT (gouv, scrolledwindow_louv, "scrolledwindow_louv");
  GLADE_HOOKUP_OBJECT (gouv, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (gouv, fixed28, "fixed28");
  GLADE_HOOKUP_OBJECT (gouv, treeview_louv, "treeview_louv");
  GLADE_HOOKUP_OBJECT (gouv, button_qgouv, "button_qgouv");
  GLADE_HOOKUP_OBJECT (gouv, alignment87, "alignment87");
  GLADE_HOOKUP_OBJECT (gouv, hbox87, "hbox87");
  GLADE_HOOKUP_OBJECT (gouv, image114, "image114");
  GLADE_HOOKUP_OBJECT (gouv, label212, "label212");

  return gouv;
}

GtkWidget*
create_ajtouv (void)
{
  GtkWidget *ajtouv;
  GtkWidget *fixed4;
  GtkWidget *image18;
  GtkWidget *entry_mbnomajt;
  GtkWidget *entry_mbpreajt;
  GtkObject *spinbutton_mbjdnajt_adj;
  GtkWidget *spinbutton_mbjdnajt;
  GtkObject *spinbutton_mbmdnajt_adj;
  GtkWidget *spinbutton_mbmdnajt;
  GtkObject *spinbutton_mbadnajt_adj;
  GtkWidget *spinbutton_mbadnajt;
  GtkWidget *entry_mbidajt;
  GtkWidget *entry_mbssajt;
  GtkWidget *button_mbcnfajt;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image19;
  GtkWidget *label27;
  GtkWidget *button_mbanlajt;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image20;
  GtkWidget *label28;
  GtkWidget *label_mbidajt;
  GtkWidget *label_mbnomajt;
  GtkWidget *label_mbpreajt;
  GtkWidget *label_mbsexeajt;
  GtkWidget *label_mbdnajt;
  GtkWidget *label_mbssajt;
  GtkWidget *label_mbtfajt;
  GtkWidget *radiobutton_mbfajt;
  GSList *radiobutton_mbfajt_group = NULL;
  GtkWidget *combobox_mbtfaj;
  GtkWidget *radiobutton_mbmajt;
  GtkWidget *button_qajouv;
  GtkWidget *alignment88;
  GtkWidget *hbox88;
  GtkWidget *image115;
  GtkWidget *label213;
  GtkWidget *label_mbspreaj;
  GtkWidget *label_mbsnsaj;
  GtkWidget *label_mbaltaj;
  GtkWidget *label_mbsnomaj;

  ajtouv = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ajtouv, 620, 430);
  gtk_window_set_title (GTK_WINDOW (ajtouv), _("Ajout ouvrier"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (ajtouv), fixed4);

  image18 = create_pixmap (ajtouv, "ouv4.jpg");
  gtk_widget_show (image18);
  gtk_fixed_put (GTK_FIXED (fixed4), image18, 0, 0);
  gtk_widget_set_size_request (image18, 620, 430);

  entry_mbnomajt = gtk_entry_new ();
  gtk_widget_show (entry_mbnomajt);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_mbnomajt, 288, 40);
  gtk_widget_set_size_request (entry_mbnomajt, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mbnomajt), 8226);

  entry_mbpreajt = gtk_entry_new ();
  gtk_widget_show (entry_mbpreajt);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_mbpreajt, 288, 80);
  gtk_widget_set_size_request (entry_mbpreajt, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mbpreajt), 8226);

  spinbutton_mbjdnajt_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_mbjdnajt = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mbjdnajt_adj), 1, 0);
  gtk_widget_show (spinbutton_mbjdnajt);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton_mbjdnajt, 288, 160);
  gtk_widget_set_size_request (spinbutton_mbjdnajt, 60, 27);

  spinbutton_mbmdnajt_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_mbmdnajt = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mbmdnajt_adj), 1, 0);
  gtk_widget_show (spinbutton_mbmdnajt);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton_mbmdnajt, 368, 160);
  gtk_widget_set_size_request (spinbutton_mbmdnajt, 60, 27);

  spinbutton_mbadnajt_adj = gtk_adjustment_new (2020, 1900, 2100, 1, 10, 10);
  spinbutton_mbadnajt = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mbadnajt_adj), 1, 0);
  gtk_widget_show (spinbutton_mbadnajt);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton_mbadnajt, 448, 160);
  gtk_widget_set_size_request (spinbutton_mbadnajt, 60, 27);

  entry_mbidajt = gtk_entry_new ();
  gtk_widget_show (entry_mbidajt);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_mbidajt, 288, 5);
  gtk_widget_set_size_request (entry_mbidajt, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mbidajt), 8226);

  entry_mbssajt = gtk_entry_new ();
  gtk_widget_show (entry_mbssajt);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_mbssajt, 288, 200);
  gtk_widget_set_size_request (entry_mbssajt, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mbssajt), 8226);

  button_mbcnfajt = gtk_button_new ();
  gtk_widget_show (button_mbcnfajt);
  gtk_fixed_put (GTK_FIXED (fixed4), button_mbcnfajt, 250, 400);
  gtk_widget_set_size_request (button_mbcnfajt, 105, 29);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button_mbcnfajt), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image19 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox15), image19, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("<span><b>confirmer</b></span>"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox15), label27, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  button_mbanlajt = gtk_button_new ();
  gtk_widget_show (button_mbanlajt);
  gtk_fixed_put (GTK_FIXED (fixed4), button_mbanlajt, 400, 400);
  gtk_widget_set_size_request (button_mbanlajt, 105, 29);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button_mbanlajt), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image20 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox16), image20, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("<span><b>annuler</b></span>"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox16), label28, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  label_mbidajt = gtk_label_new (_("<span><b>Identifiant :</b></span>"));
  gtk_widget_show (label_mbidajt);
  gtk_fixed_put (GTK_FIXED (fixed4), label_mbidajt, 136, 0);
  gtk_widget_set_size_request (label_mbidajt, 121, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mbidajt), TRUE);

  label_mbnomajt = gtk_label_new (_("<span><b>Nom :</b></span>"));
  gtk_widget_show (label_mbnomajt);
  gtk_fixed_put (GTK_FIXED (fixed4), label_mbnomajt, 184, 40);
  gtk_widget_set_size_request (label_mbnomajt, 65, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_mbnomajt), TRUE);

  label_mbpreajt = gtk_label_new (_("<span><b>Prenom :</b></span>"));
  gtk_widget_show (label_mbpreajt);
  gtk_fixed_put (GTK_FIXED (fixed4), label_mbpreajt, 160, 80);
  gtk_widget_set_size_request (label_mbpreajt, 88, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_mbpreajt), TRUE);

  label_mbsexeajt = gtk_label_new (_("<span><b>Sexe :</b></span>"));
  gtk_widget_show (label_mbsexeajt);
  gtk_fixed_put (GTK_FIXED (fixed4), label_mbsexeajt, 176, 120);
  gtk_widget_set_size_request (label_mbsexeajt, 80, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_mbsexeajt), TRUE);

  label_mbdnajt = gtk_label_new (_("<span><b>Date de naissance :</b></span>"));
  gtk_widget_show (label_mbdnajt);
  gtk_fixed_put (GTK_FIXED (fixed4), label_mbdnajt, 88, 152);
  gtk_widget_set_size_request (label_mbdnajt, 160, 41);
  gtk_label_set_use_markup (GTK_LABEL (label_mbdnajt), TRUE);

  label_mbssajt = gtk_label_new (_("<span><b>Num securite sociale :</b></span>"));
  gtk_widget_show (label_mbssajt);
  gtk_fixed_put (GTK_FIXED (fixed4), label_mbssajt, 72, 192);
  gtk_widget_set_size_request (label_mbssajt, 168, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mbssajt), TRUE);

  label_mbtfajt = gtk_label_new (_("<span><b>Tache a faire :</b></span>"));
  gtk_widget_show (label_mbtfajt);
  gtk_fixed_put (GTK_FIXED (fixed4), label_mbtfajt, 120, 232);
  gtk_widget_set_size_request (label_mbtfajt, 129, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mbtfajt), TRUE);

  radiobutton_mbfajt = gtk_radio_button_new_with_mnemonic (NULL, _("F"));
  gtk_widget_show (radiobutton_mbfajt);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton_mbfajt, 376, 120);
  gtk_widget_set_size_request (radiobutton_mbfajt, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_mbfajt), radiobutton_mbfajt_group);
  radiobutton_mbfajt_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_mbfajt));

  combobox_mbtfaj = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_mbtfaj);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox_mbtfaj, 288, 240);
  gtk_widget_set_size_request (combobox_mbtfaj, 160, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbtfaj), _("Occupation_troupeaux"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbtfaj), _("Semer"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbtfaj), _("Recolter"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbtfaj), _("Planter"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbtfaj), _("Soin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbtfaj), _("Occupation_machine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbtfaj), _("Entretien "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbtfaj), _("Securite"));

  radiobutton_mbmajt = gtk_radio_button_new_with_mnemonic (NULL, _("M"));
  gtk_widget_show (radiobutton_mbmajt);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton_mbmajt, 288, 120);
  gtk_widget_set_size_request (radiobutton_mbmajt, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_mbmajt), radiobutton_mbfajt_group);
  radiobutton_mbfajt_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_mbmajt));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton_mbmajt), TRUE);

  button_qajouv = gtk_button_new ();
  gtk_widget_show (button_qajouv);
  gtk_fixed_put (GTK_FIXED (fixed4), button_qajouv, 535, 0);
  gtk_widget_set_size_request (button_qajouv, 85, 29);

  alignment88 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment88);
  gtk_container_add (GTK_CONTAINER (button_qajouv), alignment88);

  hbox88 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox88);
  gtk_container_add (GTK_CONTAINER (alignment88), hbox88);

  image115 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image115);
  gtk_box_pack_start (GTK_BOX (hbox88), image115, FALSE, FALSE, 0);

  label213 = gtk_label_new_with_mnemonic (_("<span><b>quitter</b></span>"));
  gtk_widget_show (label213);
  gtk_box_pack_start (GTK_BOX (hbox88), label213, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label213), TRUE);

  label_mbspreaj = gtk_label_new (_("<span foreground=\"blue\" ><b>*champ obligatoire</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label_mbspreaj, 456, 80);
  gtk_widget_set_size_request (label_mbspreaj, 145, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mbspreaj), TRUE);

  label_mbsnsaj = gtk_label_new (_("<span foreground=\"blue\" ><b>*champ obligatoire</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label_mbsnsaj, 464, 200);
  gtk_widget_set_size_request (label_mbsnsaj, 145, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mbsnsaj), TRUE);

  label_mbaltaj = gtk_label_new (_("<span foreground=\"red\" ><b>Identifiant existe </b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label_mbaltaj, 264, 336);
  gtk_widget_set_size_request (label_mbaltaj, 161, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mbaltaj), TRUE);

  label_mbsnomaj = gtk_label_new (_("<span foreground=\"blue\" ><b>*champ obligatoire</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label_mbsnomaj, 448, 32);
  gtk_widget_set_size_request (label_mbsnomaj, 161, 41);
  gtk_label_set_use_markup (GTK_LABEL (label_mbsnomaj), TRUE);

  g_signal_connect ((gpointer) button_mbcnfajt, "clicked",
                    G_CALLBACK (on_button_mbcnfajt_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mbanlajt, "clicked",
                    G_CALLBACK (on_button_mbanlajt_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_mbfajt, "toggled",
                    G_CALLBACK (on_radiobutton_mbfajt_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_mbmajt, "toggled",
                    G_CALLBACK (on_radiobutton_mbmajt_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_qajouv, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajtouv, ajtouv, "ajtouv");
  GLADE_HOOKUP_OBJECT (ajtouv, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (ajtouv, image18, "image18");
  GLADE_HOOKUP_OBJECT (ajtouv, entry_mbnomajt, "entry_mbnomajt");
  GLADE_HOOKUP_OBJECT (ajtouv, entry_mbpreajt, "entry_mbpreajt");
  GLADE_HOOKUP_OBJECT (ajtouv, spinbutton_mbjdnajt, "spinbutton_mbjdnajt");
  GLADE_HOOKUP_OBJECT (ajtouv, spinbutton_mbmdnajt, "spinbutton_mbmdnajt");
  GLADE_HOOKUP_OBJECT (ajtouv, spinbutton_mbadnajt, "spinbutton_mbadnajt");
  GLADE_HOOKUP_OBJECT (ajtouv, entry_mbidajt, "entry_mbidajt");
  GLADE_HOOKUP_OBJECT (ajtouv, entry_mbssajt, "entry_mbssajt");
  GLADE_HOOKUP_OBJECT (ajtouv, button_mbcnfajt, "button_mbcnfajt");
  GLADE_HOOKUP_OBJECT (ajtouv, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (ajtouv, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (ajtouv, image19, "image19");
  GLADE_HOOKUP_OBJECT (ajtouv, label27, "label27");
  GLADE_HOOKUP_OBJECT (ajtouv, button_mbanlajt, "button_mbanlajt");
  GLADE_HOOKUP_OBJECT (ajtouv, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (ajtouv, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (ajtouv, image20, "image20");
  GLADE_HOOKUP_OBJECT (ajtouv, label28, "label28");
  GLADE_HOOKUP_OBJECT (ajtouv, label_mbidajt, "label_mbidajt");
  GLADE_HOOKUP_OBJECT (ajtouv, label_mbnomajt, "label_mbnomajt");
  GLADE_HOOKUP_OBJECT (ajtouv, label_mbpreajt, "label_mbpreajt");
  GLADE_HOOKUP_OBJECT (ajtouv, label_mbsexeajt, "label_mbsexeajt");
  GLADE_HOOKUP_OBJECT (ajtouv, label_mbdnajt, "label_mbdnajt");
  GLADE_HOOKUP_OBJECT (ajtouv, label_mbssajt, "label_mbssajt");
  GLADE_HOOKUP_OBJECT (ajtouv, label_mbtfajt, "label_mbtfajt");
  GLADE_HOOKUP_OBJECT (ajtouv, radiobutton_mbfajt, "radiobutton_mbfajt");
  GLADE_HOOKUP_OBJECT (ajtouv, combobox_mbtfaj, "combobox_mbtfaj");
  GLADE_HOOKUP_OBJECT (ajtouv, radiobutton_mbmajt, "radiobutton_mbmajt");
  GLADE_HOOKUP_OBJECT (ajtouv, button_qajouv, "button_qajouv");
  GLADE_HOOKUP_OBJECT (ajtouv, alignment88, "alignment88");
  GLADE_HOOKUP_OBJECT (ajtouv, hbox88, "hbox88");
  GLADE_HOOKUP_OBJECT (ajtouv, image115, "image115");
  GLADE_HOOKUP_OBJECT (ajtouv, label213, "label213");
  GLADE_HOOKUP_OBJECT (ajtouv, label_mbspreaj, "label_mbspreaj");
  GLADE_HOOKUP_OBJECT (ajtouv, label_mbsnsaj, "label_mbsnsaj");
  GLADE_HOOKUP_OBJECT (ajtouv, label_mbaltaj, "label_mbaltaj");
  GLADE_HOOKUP_OBJECT (ajtouv, label_mbsnomaj, "label_mbsnomaj");

  return ajtouv;
}

GtkWidget*
create_mdfouv (void)
{
  GtkWidget *mdfouv;
  GtkWidget *fixed5;
  GtkWidget *entry_mbnommdf;
  GtkWidget *entry_mbpremdf;
  GtkObject *spinbutton_mbjdnmdf_adj;
  GtkWidget *spinbutton_mbjdnmdf;
  GtkObject *spinbutton_mbmdnmdf_adj;
  GtkWidget *spinbutton_mbmdnmdf;
  GtkObject *spinbutton_mbadnmdf_adj;
  GtkWidget *spinbutton_mbadnmdf;
  GtkWidget *entry_mbssmdf;
  GtkWidget *image21;
  GtkWidget *button_mbcnfmdf;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image22;
  GtkWidget *label39;
  GtkWidget *button_mbanlmdf;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image23;
  GtkWidget *label40;
  GtkWidget *label_mbtfmdf;
  GtkWidget *label_mbexemdf;
  GtkWidget *combobox_mbtamdf;
  GtkWidget *label_mbssmdf;
  GtkWidget *label_mbdnmdf;
  GtkWidget *radiobutton_mbmmdf;
  GSList *radiobutton_mbmmdf_group = NULL;
  GtkWidget *radiobutton_mbfmdf;
  GtkWidget *label_mbnommdf;
  GtkWidget *label_mbpremdf;
  GtkWidget *combobox_mbidmdf;
  GtkWidget *button_mbvldchid;
  GtkWidget *alignment83;
  GtkWidget *hbox83;
  GtkWidget *image110;
  GtkWidget *label205;
  GtkWidget *button_mbanlchid;
  GtkWidget *alignment84;
  GtkWidget *hbox84;
  GtkWidget *image111;
  GtkWidget *label206;
  GtkWidget *label_mbidmdf;
  GtkWidget *label_mbanlchid;
  GtkWidget *label_mbvldch;
  GtkWidget *button_mbchid;
  GtkWidget *alignment82;
  GtkWidget *hbox82;
  GtkWidget *image109;
  GtkWidget *label202;
  GtkWidget *button_qmdfouv;
  GtkWidget *alignment89;
  GtkWidget *hbox89;
  GtkWidget *image116;
  GtkWidget *label214;

  mdfouv = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (mdfouv, 620, 430);
  gtk_window_set_title (GTK_WINDOW (mdfouv), _("Modifier infomations ouvrier"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (mdfouv), fixed5);

  entry_mbnommdf = gtk_entry_new ();
  gtk_widget_show (entry_mbnommdf);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_mbnommdf, 304, 112);
  gtk_widget_set_size_request (entry_mbnommdf, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mbnommdf), 8226);

  entry_mbpremdf = gtk_entry_new ();
  gtk_widget_show (entry_mbpremdf);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_mbpremdf, 304, 144);
  gtk_widget_set_size_request (entry_mbpremdf, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mbpremdf), 8226);

  spinbutton_mbjdnmdf_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_mbjdnmdf = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mbjdnmdf_adj), 1, 0);
  gtk_widget_show (spinbutton_mbjdnmdf);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton_mbjdnmdf, 304, 224);
  gtk_widget_set_size_request (spinbutton_mbjdnmdf, 60, 27);

  spinbutton_mbmdnmdf_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_mbmdnmdf = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mbmdnmdf_adj), 1, 0);
  gtk_widget_show (spinbutton_mbmdnmdf);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton_mbmdnmdf, 392, 224);
  gtk_widget_set_size_request (spinbutton_mbmdnmdf, 60, 27);

  spinbutton_mbadnmdf_adj = gtk_adjustment_new (2020, 1900, 2100, 1, 10, 10);
  spinbutton_mbadnmdf = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mbadnmdf_adj), 1, 0);
  gtk_widget_show (spinbutton_mbadnmdf);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton_mbadnmdf, 480, 224);
  gtk_widget_set_size_request (spinbutton_mbadnmdf, 60, 27);

  entry_mbssmdf = gtk_entry_new ();
  gtk_widget_show (entry_mbssmdf);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_mbssmdf, 304, 264);
  gtk_widget_set_size_request (entry_mbssmdf, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mbssmdf), 8226);

  image21 = create_pixmap (mdfouv, "ouv4.jpg");
  gtk_widget_show (image21);
  gtk_fixed_put (GTK_FIXED (fixed5), image21, 0, 0);
  gtk_widget_set_size_request (image21, 620, 430);

  button_mbcnfmdf = gtk_button_new ();
  gtk_widget_show (button_mbcnfmdf);
  gtk_fixed_put (GTK_FIXED (fixed5), button_mbcnfmdf, 250, 400);
  gtk_widget_set_size_request (button_mbcnfmdf, 105, 29);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button_mbcnfmdf), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image22 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox17), image22, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("<span><b>confirmer</b></span>"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox17), label39, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label39), TRUE);

  button_mbanlmdf = gtk_button_new ();
  gtk_widget_show (button_mbanlmdf);
  gtk_fixed_put (GTK_FIXED (fixed5), button_mbanlmdf, 400, 400);
  gtk_widget_set_size_request (button_mbanlmdf, 105, 29);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button_mbanlmdf), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image23 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox18), image23, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("<span><b>annuler</b></span>"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox18), label40, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label40), TRUE);

  label_mbtfmdf = gtk_label_new (_("<span><b>Tache a faire :</b></span>"));
  gtk_widget_show (label_mbtfmdf);
  gtk_fixed_put (GTK_FIXED (fixed5), label_mbtfmdf, 152, 304);
  gtk_widget_set_size_request (label_mbtfmdf, 120, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mbtfmdf), TRUE);

  label_mbexemdf = gtk_label_new (_("<span><b>Sexe :</b></span>"));
  gtk_widget_show (label_mbexemdf);
  gtk_fixed_put (GTK_FIXED (fixed5), label_mbexemdf, 200, 184);
  gtk_widget_set_size_request (label_mbexemdf, 73, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_mbexemdf), TRUE);

  combobox_mbtamdf = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_mbtamdf);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox_mbtamdf, 304, 304);
  gtk_widget_set_size_request (combobox_mbtamdf, 160, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbtamdf), _("Occupation_troupeaux"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbtamdf), _("Semer"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbtamdf), _("Recolter"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbtamdf), _("Planter"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbtamdf), _("Soin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbtamdf), _("Occupation_machine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbtamdf), _("Entretien "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbtamdf), _("Securite"));

  label_mbssmdf = gtk_label_new (_("<span><b>Num secutite sociale :</b></span>"));
  gtk_widget_show (label_mbssmdf);
  gtk_fixed_put (GTK_FIXED (fixed5), label_mbssmdf, 104, 264);
  gtk_widget_set_size_request (label_mbssmdf, 160, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mbssmdf), TRUE);

  label_mbdnmdf = gtk_label_new (_("<span><b>Date de naissance :</b></span>"));
  gtk_widget_show (label_mbdnmdf);
  gtk_fixed_put (GTK_FIXED (fixed5), label_mbdnmdf, 112, 224);
  gtk_widget_set_size_request (label_mbdnmdf, 160, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mbdnmdf), TRUE);

  radiobutton_mbmmdf = gtk_radio_button_new_with_mnemonic (NULL, _("M"));
  gtk_widget_show (radiobutton_mbmmdf);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton_mbmmdf, 304, 184);
  gtk_widget_set_size_request (radiobutton_mbmmdf, 72, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_mbmmdf), radiobutton_mbmmdf_group);
  radiobutton_mbmmdf_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_mbmmdf));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton_mbmmdf), TRUE);

  radiobutton_mbfmdf = gtk_radio_button_new_with_mnemonic (NULL, _("F"));
  gtk_widget_show (radiobutton_mbfmdf);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton_mbfmdf, 400, 184);
  gtk_widget_set_size_request (radiobutton_mbfmdf, 72, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_mbfmdf), radiobutton_mbmmdf_group);
  radiobutton_mbmmdf_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_mbfmdf));

  label_mbnommdf = gtk_label_new (_("<span><b>Nom :</b></span>"));
  gtk_widget_show (label_mbnommdf);
  gtk_fixed_put (GTK_FIXED (fixed5), label_mbnommdf, 208, 112);
  gtk_widget_set_size_request (label_mbnommdf, 57, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_mbnommdf), TRUE);

  label_mbpremdf = gtk_label_new (_("<span><b>Prenom :</b></span>"));
  gtk_widget_show (label_mbpremdf);
  gtk_fixed_put (GTK_FIXED (fixed5), label_mbpremdf, 192, 144);
  gtk_widget_set_size_request (label_mbpremdf, 73, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_mbpremdf), TRUE);

  combobox_mbidmdf = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_mbidmdf);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox_mbidmdf, 225, 8);
  gtk_widget_set_size_request (combobox_mbidmdf, 163, 31);

  button_mbvldchid = gtk_button_new ();
  gtk_widget_show (button_mbvldchid);
  gtk_fixed_put (GTK_FIXED (fixed5), button_mbvldchid, 256, 80);
  gtk_widget_set_size_request (button_mbvldchid, 85, 29);

  alignment83 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment83);
  gtk_container_add (GTK_CONTAINER (button_mbvldchid), alignment83);

  hbox83 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox83);
  gtk_container_add (GTK_CONTAINER (alignment83), hbox83);

  image110 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image110);
  gtk_box_pack_start (GTK_BOX (hbox83), image110, FALSE, FALSE, 0);

  label205 = gtk_label_new_with_mnemonic (_("<span><b>valider</b></span>"));
  gtk_widget_show (label205);
  gtk_box_pack_start (GTK_BOX (hbox83), label205, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label205), TRUE);

  button_mbanlchid = gtk_button_new ();
  gtk_widget_show (button_mbanlchid);
  gtk_fixed_put (GTK_FIXED (fixed5), button_mbanlchid, 384, 80);
  gtk_widget_set_size_request (button_mbanlchid, 85, 29);

  alignment84 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment84);
  gtk_container_add (GTK_CONTAINER (button_mbanlchid), alignment84);

  hbox84 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox84);
  gtk_container_add (GTK_CONTAINER (alignment84), hbox84);

  image111 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image111);
  gtk_box_pack_start (GTK_BOX (hbox84), image111, FALSE, FALSE, 0);

  label206 = gtk_label_new_with_mnemonic (_("<span><b>annuler</b></span>"));
  gtk_widget_show (label206);
  gtk_box_pack_start (GTK_BOX (hbox84), label206, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label206), TRUE);

  label_mbidmdf = gtk_label_new (_("<span><b>Identifiant :</b></span>"));
  gtk_widget_show (label_mbidmdf);
  gtk_fixed_put (GTK_FIXED (fixed5), label_mbidmdf, 112, 8);
  gtk_widget_set_size_request (label_mbidmdf, 89, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mbidmdf), TRUE);

  label_mbanlchid = gtk_label_new (_("<span foreground=\"blue\" ><b>Saisir les nouvelles informations</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed5), label_mbanlchid, 192, 40);
  gtk_widget_set_size_request (label_mbanlchid, 305, 41);
  gtk_label_set_use_markup (GTK_LABEL (label_mbanlchid), TRUE);

  label_mbvldch = gtk_label_new (_("<span foreground=\"blue\" ><b>Voulez vous recuperer les informations precedentes</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed5), label_mbvldch, 128, 40);
  gtk_widget_set_size_request (label_mbvldch, 425, 41);
  gtk_label_set_use_markup (GTK_LABEL (label_mbvldch), TRUE);

  button_mbchid = gtk_button_new ();
  gtk_widget_show (button_mbchid);
  gtk_fixed_put (GTK_FIXED (fixed5), button_mbchid, 408, 8);
  gtk_widget_set_size_request (button_mbchid, 85, 29);

  alignment82 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment82);
  gtk_container_add (GTK_CONTAINER (button_mbchid), alignment82);

  hbox82 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox82);
  gtk_container_add (GTK_CONTAINER (alignment82), hbox82);

  image109 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image109);
  gtk_box_pack_start (GTK_BOX (hbox82), image109, FALSE, FALSE, 0);

  label202 = gtk_label_new_with_mnemonic (_("<span><b>charger</b></span>"));
  gtk_widget_show (label202);
  gtk_box_pack_start (GTK_BOX (hbox82), label202, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label202), TRUE);

  button_qmdfouv = gtk_button_new ();
  gtk_widget_show (button_qmdfouv);
  gtk_fixed_put (GTK_FIXED (fixed5), button_qmdfouv, 535, 0);
  gtk_widget_set_size_request (button_qmdfouv, 85, 29);

  alignment89 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment89);
  gtk_container_add (GTK_CONTAINER (button_qmdfouv), alignment89);

  hbox89 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox89);
  gtk_container_add (GTK_CONTAINER (alignment89), hbox89);

  image116 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image116);
  gtk_box_pack_start (GTK_BOX (hbox89), image116, FALSE, FALSE, 0);

  label214 = gtk_label_new_with_mnemonic (_("<span><b>quitter</b></span>"));
  gtk_widget_show (label214);
  gtk_box_pack_start (GTK_BOX (hbox89), label214, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label214), TRUE);

  g_signal_connect ((gpointer) button_mbcnfmdf, "clicked",
                    G_CALLBACK (on_button_mbcnfmdf_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mbanlmdf, "clicked",
                    G_CALLBACK (on_button_mbanlmdf_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_mbmmdf, "toggled",
                    G_CALLBACK (on_radiobutton_mbmmdf_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_mbfmdf, "toggled",
                    G_CALLBACK (on_radiobutton_mbfmdf_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_mbvldchid, "clicked",
                    G_CALLBACK (on_button_mbvldchid_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mbanlchid, "clicked",
                    G_CALLBACK (on_button_mbanlchid_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mbchid, "clicked",
                    G_CALLBACK (on_button_mbchid_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_qmdfouv, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mdfouv, mdfouv, "mdfouv");
  GLADE_HOOKUP_OBJECT (mdfouv, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (mdfouv, entry_mbnommdf, "entry_mbnommdf");
  GLADE_HOOKUP_OBJECT (mdfouv, entry_mbpremdf, "entry_mbpremdf");
  GLADE_HOOKUP_OBJECT (mdfouv, spinbutton_mbjdnmdf, "spinbutton_mbjdnmdf");
  GLADE_HOOKUP_OBJECT (mdfouv, spinbutton_mbmdnmdf, "spinbutton_mbmdnmdf");
  GLADE_HOOKUP_OBJECT (mdfouv, spinbutton_mbadnmdf, "spinbutton_mbadnmdf");
  GLADE_HOOKUP_OBJECT (mdfouv, entry_mbssmdf, "entry_mbssmdf");
  GLADE_HOOKUP_OBJECT (mdfouv, image21, "image21");
  GLADE_HOOKUP_OBJECT (mdfouv, button_mbcnfmdf, "button_mbcnfmdf");
  GLADE_HOOKUP_OBJECT (mdfouv, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (mdfouv, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (mdfouv, image22, "image22");
  GLADE_HOOKUP_OBJECT (mdfouv, label39, "label39");
  GLADE_HOOKUP_OBJECT (mdfouv, button_mbanlmdf, "button_mbanlmdf");
  GLADE_HOOKUP_OBJECT (mdfouv, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (mdfouv, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (mdfouv, image23, "image23");
  GLADE_HOOKUP_OBJECT (mdfouv, label40, "label40");
  GLADE_HOOKUP_OBJECT (mdfouv, label_mbtfmdf, "label_mbtfmdf");
  GLADE_HOOKUP_OBJECT (mdfouv, label_mbexemdf, "label_mbexemdf");
  GLADE_HOOKUP_OBJECT (mdfouv, combobox_mbtamdf, "combobox_mbtamdf");
  GLADE_HOOKUP_OBJECT (mdfouv, label_mbssmdf, "label_mbssmdf");
  GLADE_HOOKUP_OBJECT (mdfouv, label_mbdnmdf, "label_mbdnmdf");
  GLADE_HOOKUP_OBJECT (mdfouv, radiobutton_mbmmdf, "radiobutton_mbmmdf");
  GLADE_HOOKUP_OBJECT (mdfouv, radiobutton_mbfmdf, "radiobutton_mbfmdf");
  GLADE_HOOKUP_OBJECT (mdfouv, label_mbnommdf, "label_mbnommdf");
  GLADE_HOOKUP_OBJECT (mdfouv, label_mbpremdf, "label_mbpremdf");
  GLADE_HOOKUP_OBJECT (mdfouv, combobox_mbidmdf, "combobox_mbidmdf");
  GLADE_HOOKUP_OBJECT (mdfouv, button_mbvldchid, "button_mbvldchid");
  GLADE_HOOKUP_OBJECT (mdfouv, alignment83, "alignment83");
  GLADE_HOOKUP_OBJECT (mdfouv, hbox83, "hbox83");
  GLADE_HOOKUP_OBJECT (mdfouv, image110, "image110");
  GLADE_HOOKUP_OBJECT (mdfouv, label205, "label205");
  GLADE_HOOKUP_OBJECT (mdfouv, button_mbanlchid, "button_mbanlchid");
  GLADE_HOOKUP_OBJECT (mdfouv, alignment84, "alignment84");
  GLADE_HOOKUP_OBJECT (mdfouv, hbox84, "hbox84");
  GLADE_HOOKUP_OBJECT (mdfouv, image111, "image111");
  GLADE_HOOKUP_OBJECT (mdfouv, label206, "label206");
  GLADE_HOOKUP_OBJECT (mdfouv, label_mbidmdf, "label_mbidmdf");
  GLADE_HOOKUP_OBJECT (mdfouv, label_mbanlchid, "label_mbanlchid");
  GLADE_HOOKUP_OBJECT (mdfouv, label_mbvldch, "label_mbvldch");
  GLADE_HOOKUP_OBJECT (mdfouv, button_mbchid, "button_mbchid");
  GLADE_HOOKUP_OBJECT (mdfouv, alignment82, "alignment82");
  GLADE_HOOKUP_OBJECT (mdfouv, hbox82, "hbox82");
  GLADE_HOOKUP_OBJECT (mdfouv, image109, "image109");
  GLADE_HOOKUP_OBJECT (mdfouv, label202, "label202");
  GLADE_HOOKUP_OBJECT (mdfouv, button_qmdfouv, "button_qmdfouv");
  GLADE_HOOKUP_OBJECT (mdfouv, alignment89, "alignment89");
  GLADE_HOOKUP_OBJECT (mdfouv, hbox89, "hbox89");
  GLADE_HOOKUP_OBJECT (mdfouv, image116, "image116");
  GLADE_HOOKUP_OBJECT (mdfouv, label214, "label214");

  return mdfouv;
}

GtkWidget*
create_rechouv (void)
{
  GtkWidget *rechouv;
  GtkWidget *fixed6;
  GtkWidget *image24;
  GtkWidget *button_mbretrech;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image25;
  GtkWidget *label42;
  GtkWidget *entry_mbidrech;
  GtkWidget *label_mbtxtrech;
  GtkWidget *button_mbcnfrech;
  GtkWidget *alignment74;
  GtkWidget *hbox74;
  GtkWidget *image100;
  GtkWidget *label185;
  GtkWidget *label_mbaltrech;
  GtkWidget *label_mbidrech;
  GtkWidget *label_mbcrrech;
  GtkWidget *combobox_mbcrrech;
  GtkWidget *button_qrechouv;
  GtkWidget *alignment90;
  GtkWidget *hbox90;
  GtkWidget *image117;
  GtkWidget *label216;
  GtkWidget *scrolledwindow_rechouv;
  GtkWidget *viewport2;
  GtkWidget *fixed29;
  GtkWidget *treeview_mbtxtrech;

  rechouv = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (rechouv, 620, 430);
  gtk_window_set_title (GTK_WINDOW (rechouv), _("Recherche ouvrier"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (rechouv), fixed6);

  image24 = create_pixmap (rechouv, "ouv4.jpg");
  gtk_widget_show (image24);
  gtk_fixed_put (GTK_FIXED (fixed6), image24, 0, 0);
  gtk_widget_set_size_request (image24, 620, 430);

  button_mbretrech = gtk_button_new ();
  gtk_widget_show (button_mbretrech);
  gtk_fixed_put (GTK_FIXED (fixed6), button_mbretrech, 445, 0);
  gtk_widget_set_size_request (button_mbretrech, 85, 29);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button_mbretrech), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image25 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox19), image25, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("<span><b>retour</b></span>"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox19), label42, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label42), TRUE);

  entry_mbidrech = gtk_entry_new ();
  gtk_widget_show (entry_mbidrech);
  gtk_fixed_put (GTK_FIXED (fixed6), entry_mbidrech, 240, 83);
  gtk_widget_set_size_request (entry_mbidrech, 250, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mbidrech), 8226);

  label_mbtxtrech = gtk_label_new (_("<span><b>Le champ a rechercher est :</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed6), label_mbtxtrech, 88, 152);
  gtk_widget_set_size_request (label_mbtxtrech, 201, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mbtxtrech), TRUE);

  button_mbcnfrech = gtk_button_new ();
  gtk_widget_show (button_mbcnfrech);
  gtk_fixed_put (GTK_FIXED (fixed6), button_mbcnfrech, 504, 80);
  gtk_widget_set_size_request (button_mbcnfrech, 105, 29);

  alignment74 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment74);
  gtk_container_add (GTK_CONTAINER (button_mbcnfrech), alignment74);

  hbox74 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox74);
  gtk_container_add (GTK_CONTAINER (alignment74), hbox74);

  image100 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image100);
  gtk_box_pack_start (GTK_BOX (hbox74), image100, FALSE, FALSE, 0);

  label185 = gtk_label_new_with_mnemonic (_("<span><b>rechercher</b></span>"));
  gtk_widget_show (label185);
  gtk_box_pack_start (GTK_BOX (hbox74), label185, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label185), TRUE);

  label_mbaltrech = gtk_label_new (_("<span foreground=\"red\" ><b>Donn\303\251e invalide !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed6), label_mbaltrech, 296, 112);
  gtk_widget_set_size_request (label_mbaltrech, 233, 41);
  gtk_label_set_use_markup (GTK_LABEL (label_mbaltrech), TRUE);

  label_mbidrech = gtk_label_new (_("<span><b>Tapez l'identifiant a rechercher :</b></span>"));
  gtk_widget_show (label_mbidrech);
  gtk_fixed_put (GTK_FIXED (fixed6), label_mbidrech, 0, 80);
  gtk_widget_set_size_request (label_mbidrech, 241, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mbidrech), TRUE);

  label_mbcrrech = gtk_label_new (_("<span><b>Choisir le critere a rechercher :</b></span>"));
  gtk_widget_show (label_mbcrrech);
  gtk_fixed_put (GTK_FIXED (fixed6), label_mbcrrech, 16, 24);
  gtk_widget_set_size_request (label_mbcrrech, 249, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mbcrrech), TRUE);

  combobox_mbcrrech = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_mbcrrech);
  gtk_fixed_put (GTK_FIXED (fixed6), combobox_mbcrrech, 272, 27);
  gtk_widget_set_size_request (combobox_mbcrrech, 163, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbcrrech), _("identifiant"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbcrrech), _("nom"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbcrrech), _("prenom"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbcrrech), _("securite_sociale"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbcrrech), _("tache"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mbcrrech), _("annee_naissance"));

  button_qrechouv = gtk_button_new ();
  gtk_widget_show (button_qrechouv);
  gtk_fixed_put (GTK_FIXED (fixed6), button_qrechouv, 535, 0);
  gtk_widget_set_size_request (button_qrechouv, 85, 29);

  alignment90 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment90);
  gtk_container_add (GTK_CONTAINER (button_qrechouv), alignment90);

  hbox90 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox90);
  gtk_container_add (GTK_CONTAINER (alignment90), hbox90);

  image117 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image117);
  gtk_box_pack_start (GTK_BOX (hbox90), image117, FALSE, FALSE, 0);

  label216 = gtk_label_new_with_mnemonic (_("<span><b>quitter</b></span>"));
  gtk_widget_show (label216);
  gtk_box_pack_start (GTK_BOX (hbox90), label216, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label216), TRUE);

  scrolledwindow_rechouv = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow_rechouv);
  gtk_fixed_put (GTK_FIXED (fixed6), scrolledwindow_rechouv, 0, 200);
  gtk_widget_set_size_request (scrolledwindow_rechouv, 620, 220);

  viewport2 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow_rechouv), viewport2);

  fixed29 = gtk_fixed_new ();
  gtk_widget_show (fixed29);
  gtk_container_add (GTK_CONTAINER (viewport2), fixed29);

  treeview_mbtxtrech = gtk_tree_view_new ();
  gtk_widget_show (treeview_mbtxtrech);
  gtk_fixed_put (GTK_FIXED (fixed29), treeview_mbtxtrech, 0, 0);
  gtk_widget_set_size_request (treeview_mbtxtrech, 800, 1500);

  g_signal_connect ((gpointer) button_mbretrech, "clicked",
                    G_CALLBACK (on_button_mbretrech_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mbcnfrech, "clicked",
                    G_CALLBACK (on_button_mbcnfrech_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_qrechouv, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) treeview_mbtxtrech, "row_activated",
                    G_CALLBACK (on_treeview_mbtxtrech_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (rechouv, rechouv, "rechouv");
  GLADE_HOOKUP_OBJECT (rechouv, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (rechouv, image24, "image24");
  GLADE_HOOKUP_OBJECT (rechouv, button_mbretrech, "button_mbretrech");
  GLADE_HOOKUP_OBJECT (rechouv, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (rechouv, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (rechouv, image25, "image25");
  GLADE_HOOKUP_OBJECT (rechouv, label42, "label42");
  GLADE_HOOKUP_OBJECT (rechouv, entry_mbidrech, "entry_mbidrech");
  GLADE_HOOKUP_OBJECT (rechouv, label_mbtxtrech, "label_mbtxtrech");
  GLADE_HOOKUP_OBJECT (rechouv, button_mbcnfrech, "button_mbcnfrech");
  GLADE_HOOKUP_OBJECT (rechouv, alignment74, "alignment74");
  GLADE_HOOKUP_OBJECT (rechouv, hbox74, "hbox74");
  GLADE_HOOKUP_OBJECT (rechouv, image100, "image100");
  GLADE_HOOKUP_OBJECT (rechouv, label185, "label185");
  GLADE_HOOKUP_OBJECT (rechouv, label_mbaltrech, "label_mbaltrech");
  GLADE_HOOKUP_OBJECT (rechouv, label_mbidrech, "label_mbidrech");
  GLADE_HOOKUP_OBJECT (rechouv, label_mbcrrech, "label_mbcrrech");
  GLADE_HOOKUP_OBJECT (rechouv, combobox_mbcrrech, "combobox_mbcrrech");
  GLADE_HOOKUP_OBJECT (rechouv, button_qrechouv, "button_qrechouv");
  GLADE_HOOKUP_OBJECT (rechouv, alignment90, "alignment90");
  GLADE_HOOKUP_OBJECT (rechouv, hbox90, "hbox90");
  GLADE_HOOKUP_OBJECT (rechouv, image117, "image117");
  GLADE_HOOKUP_OBJECT (rechouv, label216, "label216");
  GLADE_HOOKUP_OBJECT (rechouv, scrolledwindow_rechouv, "scrolledwindow_rechouv");
  GLADE_HOOKUP_OBJECT (rechouv, viewport2, "viewport2");
  GLADE_HOOKUP_OBJECT (rechouv, fixed29, "fixed29");
  GLADE_HOOKUP_OBJECT (rechouv, treeview_mbtxtrech, "treeview_mbtxtrech");

  return rechouv;
}

GtkWidget*
create_absouv (void)
{
  GtkWidget *absouv;
  GtkWidget *fixed26;
  GtkObject *spinbutton_mbjabs_adj;
  GtkWidget *spinbutton_mbjabs;
  GtkObject *spinbutton_mbmabs_adj;
  GtkWidget *spinbutton_mbmabs;
  GtkObject *spinbutton_mbaabs_adj;
  GtkWidget *spinbutton_mbaabs;
  GtkWidget *image101;
  GtkWidget *combobox_mbidabs;
  GtkWidget *button_mbretabs;
  GtkWidget *alignment77;
  GtkWidget *hbox77;
  GtkWidget *image104;
  GtkWidget *label191;
  GtkWidget *button_qgabsouv;
  GtkWidget *alignment91;
  GtkWidget *hbox91;
  GtkWidget *image118;
  GtkWidget *label217;
  GtkWidget *scrolledwindow_tabsouv;
  GtkWidget *viewport3;
  GtkWidget *fixed30;
  GtkWidget *treeview_mbabs;
  GtkWidget *button_mbtabs;
  GtkWidget *alignment76;
  GtkWidget *hbox76;
  GtkWidget *image103;
  GtkWidget *label190;
  GtkWidget *button_mbcnfabs;
  GtkWidget *alignment75;
  GtkWidget *hbox75;
  GtkWidget *image102;
  GtkWidget *label189;
  GtkWidget *button_mbmdfabs;
  GtkWidget *alignment78;
  GtkWidget *hbox78;
  GtkWidget *image105;
  GtkWidget *label192;
  GtkWidget *button_mbspabs;
  GtkWidget *alignment86;
  GtkWidget *hbox86;
  GtkWidget *image113;
  GtkWidget *label211;
  GtkWidget *label_mbidabs;
  GtkWidget *label_mbdtabs;
  GtkWidget *label_mbabsabs;
  GtkWidget *checkbutton_mboabs;
  GtkWidget *button_mbchidabs;
  GtkWidget *alignment85;
  GtkWidget *hbox85;
  GtkWidget *image112;
  GtkWidget *label210;
  GtkWidget *label_mbscajabs;
  GtkWidget *label_mbscmdfabs;
  GtkWidget *label_mbscspabs;
  GtkObject *spinbutton1_mbmaffabs_adj;
  GtkWidget *spinbutton1_mbmaffabs;
  GtkObject *spinbutton_mbaaffabs_adj;
  GtkWidget *spinbutton_mbaaffabs;
  GtkWidget *label_mbaffabs;
  GtkWidget *label_mbvrdate;

  absouv = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (absouv, 620, 430);
  gtk_window_set_title (GTK_WINDOW (absouv), _("Gestion Absentisme Ouvrier"));

  fixed26 = gtk_fixed_new ();
  gtk_widget_show (fixed26);
  gtk_container_add (GTK_CONTAINER (absouv), fixed26);

  spinbutton_mbjabs_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_mbjabs = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mbjabs_adj), 1, 0);
  gtk_widget_show (spinbutton_mbjabs);
  gtk_fixed_put (GTK_FIXED (fixed26), spinbutton_mbjabs, 184, 64);
  gtk_widget_set_size_request (spinbutton_mbjabs, 60, 27);

  spinbutton_mbmabs_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_mbmabs = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mbmabs_adj), 1, 0);
  gtk_widget_show (spinbutton_mbmabs);
  gtk_fixed_put (GTK_FIXED (fixed26), spinbutton_mbmabs, 264, 64);
  gtk_widget_set_size_request (spinbutton_mbmabs, 60, 27);

  spinbutton_mbaabs_adj = gtk_adjustment_new (2020, 1900, 2100, 1, 10, 10);
  spinbutton_mbaabs = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mbaabs_adj), 1, 0);
  gtk_widget_show (spinbutton_mbaabs);
  gtk_fixed_put (GTK_FIXED (fixed26), spinbutton_mbaabs, 344, 64);
  gtk_widget_set_size_request (spinbutton_mbaabs, 60, 27);

  image101 = create_pixmap (absouv, "crop-farmer.png");
  gtk_widget_show (image101);
  gtk_fixed_put (GTK_FIXED (fixed26), image101, 0, 0);
  gtk_widget_set_size_request (image101, 620, 430);

  combobox_mbidabs = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_mbidabs);
  gtk_fixed_put (GTK_FIXED (fixed26), combobox_mbidabs, 183, 21);
  gtk_widget_set_size_request (combobox_mbidabs, 165, 31);

  button_mbretabs = gtk_button_new ();
  gtk_widget_show (button_mbretabs);
  gtk_fixed_put (GTK_FIXED (fixed26), button_mbretabs, 445, 0);
  gtk_widget_set_size_request (button_mbretabs, 85, 29);

  alignment77 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment77);
  gtk_container_add (GTK_CONTAINER (button_mbretabs), alignment77);

  hbox77 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox77);
  gtk_container_add (GTK_CONTAINER (alignment77), hbox77);

  image104 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image104);
  gtk_box_pack_start (GTK_BOX (hbox77), image104, FALSE, FALSE, 0);

  label191 = gtk_label_new_with_mnemonic (_("<span><b>retour</b></span>"));
  gtk_widget_show (label191);
  gtk_box_pack_start (GTK_BOX (hbox77), label191, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label191), TRUE);

  button_qgabsouv = gtk_button_new ();
  gtk_widget_show (button_qgabsouv);
  gtk_fixed_put (GTK_FIXED (fixed26), button_qgabsouv, 535, 0);
  gtk_widget_set_size_request (button_qgabsouv, 85, 29);

  alignment91 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment91);
  gtk_container_add (GTK_CONTAINER (button_qgabsouv), alignment91);

  hbox91 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox91);
  gtk_container_add (GTK_CONTAINER (alignment91), hbox91);

  image118 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image118);
  gtk_box_pack_start (GTK_BOX (hbox91), image118, FALSE, FALSE, 0);

  label217 = gtk_label_new_with_mnemonic (_("<span><b>quitter</b></span>"));
  gtk_widget_show (label217);
  gtk_box_pack_start (GTK_BOX (hbox91), label217, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label217), TRUE);

  scrolledwindow_tabsouv = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow_tabsouv);
  gtk_fixed_put (GTK_FIXED (fixed26), scrolledwindow_tabsouv, 50, 232);
  gtk_widget_set_size_request (scrolledwindow_tabsouv, 500, 200);

  viewport3 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow_tabsouv), viewport3);

  fixed30 = gtk_fixed_new ();
  gtk_widget_show (fixed30);
  gtk_container_add (GTK_CONTAINER (viewport3), fixed30);

  treeview_mbabs = gtk_tree_view_new ();
  gtk_widget_show (treeview_mbabs);
  gtk_fixed_put (GTK_FIXED (fixed30), treeview_mbabs, 0, 0);
  gtk_widget_set_size_request (treeview_mbabs, 486, 10000);

  button_mbtabs = gtk_button_new ();
  gtk_widget_show (button_mbtabs);
  gtk_fixed_put (GTK_FIXED (fixed26), button_mbtabs, 40, 152);
  gtk_widget_set_size_request (button_mbtabs, 105, 29);

  alignment76 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment76);
  gtk_container_add (GTK_CONTAINER (button_mbtabs), alignment76);

  hbox76 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox76);
  gtk_container_add (GTK_CONTAINER (alignment76), hbox76);

  image103 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image103);
  gtk_box_pack_start (GTK_BOX (hbox76), image103, FALSE, FALSE, 0);

  label190 = gtk_label_new_with_mnemonic (_("<span><b>afficher</b></span>"));
  gtk_widget_show (label190);
  gtk_box_pack_start (GTK_BOX (hbox76), label190, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label190), TRUE);

  button_mbcnfabs = gtk_button_new ();
  gtk_widget_show (button_mbcnfabs);
  gtk_fixed_put (GTK_FIXED (fixed26), button_mbcnfabs, 200, 152);
  gtk_widget_set_size_request (button_mbcnfabs, 105, 29);

  alignment75 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment75);
  gtk_container_add (GTK_CONTAINER (button_mbcnfabs), alignment75);

  hbox75 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox75);
  gtk_container_add (GTK_CONTAINER (alignment75), hbox75);

  image102 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image102);
  gtk_box_pack_start (GTK_BOX (hbox75), image102, FALSE, FALSE, 0);

  label189 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>ajouter</b></span>"));
  gtk_widget_show (label189);
  gtk_box_pack_start (GTK_BOX (hbox75), label189, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label189), TRUE);

  button_mbmdfabs = gtk_button_new ();
  gtk_widget_show (button_mbmdfabs);
  gtk_fixed_put (GTK_FIXED (fixed26), button_mbmdfabs, 360, 152);
  gtk_widget_set_size_request (button_mbmdfabs, 105, 29);

  alignment78 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment78);
  gtk_container_add (GTK_CONTAINER (button_mbmdfabs), alignment78);

  hbox78 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox78);
  gtk_container_add (GTK_CONTAINER (alignment78), hbox78);

  image105 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image105);
  gtk_box_pack_start (GTK_BOX (hbox78), image105, FALSE, FALSE, 0);

  label192 = gtk_label_new_with_mnemonic (_("<span><b>modifier</b></span>"));
  gtk_widget_show (label192);
  gtk_box_pack_start (GTK_BOX (hbox78), label192, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label192), TRUE);

  button_mbspabs = gtk_button_new ();
  gtk_widget_show (button_mbspabs);
  gtk_fixed_put (GTK_FIXED (fixed26), button_mbspabs, 512, 152);
  gtk_widget_set_size_request (button_mbspabs, 105, 29);

  alignment86 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment86);
  gtk_container_add (GTK_CONTAINER (button_mbspabs), alignment86);

  hbox86 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox86);
  gtk_container_add (GTK_CONTAINER (alignment86), hbox86);

  image113 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image113);
  gtk_box_pack_start (GTK_BOX (hbox86), image113, FALSE, FALSE, 0);

  label211 = gtk_label_new_with_mnemonic (_("<span><b>supprimer</b></span>"));
  gtk_widget_show (label211);
  gtk_box_pack_start (GTK_BOX (hbox86), label211, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label211), TRUE);

  label_mbidabs = gtk_label_new (_("<span><b>Identifiant :</b></span>"));
  gtk_widget_show (label_mbidabs);
  gtk_fixed_put (GTK_FIXED (fixed26), label_mbidabs, 72, 24);
  gtk_widget_set_size_request (label_mbidabs, 105, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_mbidabs), TRUE);

  label_mbdtabs = gtk_label_new (_("<span><b>Date :</b></span>"));
  gtk_widget_show (label_mbdtabs);
  gtk_fixed_put (GTK_FIXED (fixed26), label_mbdtabs, 112, 64);
  gtk_widget_set_size_request (label_mbdtabs, 65, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_mbdtabs), TRUE);

  label_mbabsabs = gtk_label_new (_("<span><b>Absentisme :</b></span>"));
  gtk_widget_show (label_mbabsabs);
  gtk_fixed_put (GTK_FIXED (fixed26), label_mbabsabs, 64, 96);
  gtk_widget_set_size_request (label_mbabsabs, 113, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mbabsabs), TRUE);

  checkbutton_mboabs = gtk_check_button_new_with_mnemonic (_("Oui"));
  gtk_widget_show (checkbutton_mboabs);
  gtk_fixed_put (GTK_FIXED (fixed26), checkbutton_mboabs, 184, 104);
  gtk_widget_set_size_request (checkbutton_mboabs, 80, 24);

  button_mbchidabs = gtk_button_new ();
  gtk_widget_show (button_mbchidabs);
  gtk_fixed_put (GTK_FIXED (fixed26), button_mbchidabs, 360, 24);
  gtk_widget_set_size_request (button_mbchidabs, 85, 29);

  alignment85 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment85);
  gtk_container_add (GTK_CONTAINER (button_mbchidabs), alignment85);

  hbox85 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox85);
  gtk_container_add (GTK_CONTAINER (alignment85), hbox85);

  image112 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image112);
  gtk_box_pack_start (GTK_BOX (hbox85), image112, FALSE, FALSE, 0);

  label210 = gtk_label_new_with_mnemonic (_("<span><b>charger</b></span>"));
  gtk_widget_show (label210);
  gtk_box_pack_start (GTK_BOX (hbox85), label210, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label210), TRUE);

  label_mbscajabs = gtk_label_new (_("<span foreground=\"green\" ><b>Ajout avec succes</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed26), label_mbscajabs, 376, 112);
  gtk_widget_set_size_request (label_mbscajabs, 137, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mbscajabs), TRUE);

  label_mbscmdfabs = gtk_label_new (_("<span foreground=\"green\" ><b>Modification avec succes</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed26), label_mbscmdfabs, 392, 112);
  gtk_widget_set_size_request (label_mbscmdfabs, 185, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mbscmdfabs), TRUE);

  label_mbscspabs = gtk_label_new (_("<span foreground=\"green\" ><b>Suppression avec succes</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed26), label_mbscspabs, 384, 112);
  gtk_widget_set_size_request (label_mbscspabs, 201, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mbscspabs), TRUE);

  spinbutton1_mbmaffabs_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton1_mbmaffabs = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_mbmaffabs_adj), 1, 0);
  gtk_widget_show (spinbutton1_mbmaffabs);
  gtk_fixed_put (GTK_FIXED (fixed26), spinbutton1_mbmaffabs, 264, 192);
  gtk_widget_set_size_request (spinbutton1_mbmaffabs, 60, 27);

  spinbutton_mbaaffabs_adj = gtk_adjustment_new (2020, 1900, 2100, 1, 10, 10);
  spinbutton_mbaaffabs = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mbaaffabs_adj), 1, 0);
  gtk_widget_show (spinbutton_mbaaffabs);
  gtk_fixed_put (GTK_FIXED (fixed26), spinbutton_mbaaffabs, 344, 192);
  gtk_widget_set_size_request (spinbutton_mbaaffabs, 60, 27);

  label_mbaffabs = gtk_label_new (_("<span foreground=\"blue\" ><b>Tapez la date :</b></span>"));
  gtk_widget_show (label_mbaffabs);
  gtk_fixed_put (GTK_FIXED (fixed26), label_mbaffabs, 112, 184);
  gtk_widget_set_size_request (label_mbaffabs, 169, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mbaffabs), TRUE);

  label_mbvrdate = gtk_label_new (_("<span foreground=\"red\" ><b>Date deje remplie !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed26), label_mbvrdate, 416, 64);
  gtk_widget_set_size_request (label_mbvrdate, 193, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mbvrdate), TRUE);

  g_signal_connect ((gpointer) button_mbretabs, "clicked",
                    G_CALLBACK (on_button_mbretabs_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_qgabsouv, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) treeview_mbabs, "row_activated",
                    G_CALLBACK (on_treeview_mbabs_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_mbtabs, "clicked",
                    G_CALLBACK (on_button_mbtabs_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mbcnfabs, "clicked",
                    G_CALLBACK (on_button_mbcnfabs_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mbmdfabs, "clicked",
                    G_CALLBACK (on_button_mbmdfabs_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mbspabs, "clicked",
                    G_CALLBACK (on_button_mbspabs_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_mboabs, "toggled",
                    G_CALLBACK (on_checkbutton_mboabs_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_mbchidabs, "clicked",
                    G_CALLBACK (on_button_mbchidabs_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (absouv, absouv, "absouv");
  GLADE_HOOKUP_OBJECT (absouv, fixed26, "fixed26");
  GLADE_HOOKUP_OBJECT (absouv, spinbutton_mbjabs, "spinbutton_mbjabs");
  GLADE_HOOKUP_OBJECT (absouv, spinbutton_mbmabs, "spinbutton_mbmabs");
  GLADE_HOOKUP_OBJECT (absouv, spinbutton_mbaabs, "spinbutton_mbaabs");
  GLADE_HOOKUP_OBJECT (absouv, image101, "image101");
  GLADE_HOOKUP_OBJECT (absouv, combobox_mbidabs, "combobox_mbidabs");
  GLADE_HOOKUP_OBJECT (absouv, button_mbretabs, "button_mbretabs");
  GLADE_HOOKUP_OBJECT (absouv, alignment77, "alignment77");
  GLADE_HOOKUP_OBJECT (absouv, hbox77, "hbox77");
  GLADE_HOOKUP_OBJECT (absouv, image104, "image104");
  GLADE_HOOKUP_OBJECT (absouv, label191, "label191");
  GLADE_HOOKUP_OBJECT (absouv, button_qgabsouv, "button_qgabsouv");
  GLADE_HOOKUP_OBJECT (absouv, alignment91, "alignment91");
  GLADE_HOOKUP_OBJECT (absouv, hbox91, "hbox91");
  GLADE_HOOKUP_OBJECT (absouv, image118, "image118");
  GLADE_HOOKUP_OBJECT (absouv, label217, "label217");
  GLADE_HOOKUP_OBJECT (absouv, scrolledwindow_tabsouv, "scrolledwindow_tabsouv");
  GLADE_HOOKUP_OBJECT (absouv, viewport3, "viewport3");
  GLADE_HOOKUP_OBJECT (absouv, fixed30, "fixed30");
  GLADE_HOOKUP_OBJECT (absouv, treeview_mbabs, "treeview_mbabs");
  GLADE_HOOKUP_OBJECT (absouv, button_mbtabs, "button_mbtabs");
  GLADE_HOOKUP_OBJECT (absouv, alignment76, "alignment76");
  GLADE_HOOKUP_OBJECT (absouv, hbox76, "hbox76");
  GLADE_HOOKUP_OBJECT (absouv, image103, "image103");
  GLADE_HOOKUP_OBJECT (absouv, label190, "label190");
  GLADE_HOOKUP_OBJECT (absouv, button_mbcnfabs, "button_mbcnfabs");
  GLADE_HOOKUP_OBJECT (absouv, alignment75, "alignment75");
  GLADE_HOOKUP_OBJECT (absouv, hbox75, "hbox75");
  GLADE_HOOKUP_OBJECT (absouv, image102, "image102");
  GLADE_HOOKUP_OBJECT (absouv, label189, "label189");
  GLADE_HOOKUP_OBJECT (absouv, button_mbmdfabs, "button_mbmdfabs");
  GLADE_HOOKUP_OBJECT (absouv, alignment78, "alignment78");
  GLADE_HOOKUP_OBJECT (absouv, hbox78, "hbox78");
  GLADE_HOOKUP_OBJECT (absouv, image105, "image105");
  GLADE_HOOKUP_OBJECT (absouv, label192, "label192");
  GLADE_HOOKUP_OBJECT (absouv, button_mbspabs, "button_mbspabs");
  GLADE_HOOKUP_OBJECT (absouv, alignment86, "alignment86");
  GLADE_HOOKUP_OBJECT (absouv, hbox86, "hbox86");
  GLADE_HOOKUP_OBJECT (absouv, image113, "image113");
  GLADE_HOOKUP_OBJECT (absouv, label211, "label211");
  GLADE_HOOKUP_OBJECT (absouv, label_mbidabs, "label_mbidabs");
  GLADE_HOOKUP_OBJECT (absouv, label_mbdtabs, "label_mbdtabs");
  GLADE_HOOKUP_OBJECT (absouv, label_mbabsabs, "label_mbabsabs");
  GLADE_HOOKUP_OBJECT (absouv, checkbutton_mboabs, "checkbutton_mboabs");
  GLADE_HOOKUP_OBJECT (absouv, button_mbchidabs, "button_mbchidabs");
  GLADE_HOOKUP_OBJECT (absouv, alignment85, "alignment85");
  GLADE_HOOKUP_OBJECT (absouv, hbox85, "hbox85");
  GLADE_HOOKUP_OBJECT (absouv, image112, "image112");
  GLADE_HOOKUP_OBJECT (absouv, label210, "label210");
  GLADE_HOOKUP_OBJECT (absouv, label_mbscajabs, "label_mbscajabs");
  GLADE_HOOKUP_OBJECT (absouv, label_mbscmdfabs, "label_mbscmdfabs");
  GLADE_HOOKUP_OBJECT (absouv, label_mbscspabs, "label_mbscspabs");
  GLADE_HOOKUP_OBJECT (absouv, spinbutton1_mbmaffabs, "spinbutton1_mbmaffabs");
  GLADE_HOOKUP_OBJECT (absouv, spinbutton_mbaaffabs, "spinbutton_mbaaffabs");
  GLADE_HOOKUP_OBJECT (absouv, label_mbaffabs, "label_mbaffabs");
  GLADE_HOOKUP_OBJECT (absouv, label_mbvrdate, "label_mbvrdate");

  return absouv;
}

GtkWidget*
create_suppouv (void)
{
  GtkWidget *suppouv;
  GtkWidget *fixed27;
  GtkWidget *entry_mbidsp;
  GtkWidget *image119;
  GtkWidget *label_mbidsp;
  GtkWidget *button_mbcnfsp;
  GtkWidget *alignment79;
  GtkWidget *hbox79;
  GtkWidget *image106;
  GtkWidget *label194;
  GtkWidget *button_mbanlsp;
  GtkWidget *alignment80;
  GtkWidget *hbox80;
  GtkWidget *image107;
  GtkWidget *label195;
  GtkWidget *button_qspouv;
  GtkWidget *alignment92;
  GtkWidget *hbox92;
  GtkWidget *image120;
  GtkWidget *label218;
  GtkWidget *label_mbcnfsp;
  GtkWidget *radiobutton_mbnsp;
  GSList *radiobutton_mbnsp_group = NULL;
  GtkWidget *alignment96;
  GtkWidget *hbox96;
  GtkWidget *image127;
  GtkWidget *label222;
  GtkWidget *radiobutton_mbosp;
  GtkWidget *alignment97;
  GtkWidget *hbox97;
  GtkWidget *image128;
  GtkWidget *label223;
  GtkWidget *label_mbaltsp;

  suppouv = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (suppouv, 620, 430);
  gtk_window_set_title (GTK_WINDOW (suppouv), _("Suppression Ouvrier"));

  fixed27 = gtk_fixed_new ();
  gtk_widget_show (fixed27);
  gtk_container_add (GTK_CONTAINER (suppouv), fixed27);

  entry_mbidsp = gtk_entry_new ();
  gtk_widget_show (entry_mbidsp);
  gtk_fixed_put (GTK_FIXED (fixed27), entry_mbidsp, 200, 56);
  gtk_widget_set_size_request (entry_mbidsp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mbidsp), 8226);

  image119 = create_pixmap (suppouv, "ouv4.jpg");
  gtk_widget_show (image119);
  gtk_fixed_put (GTK_FIXED (fixed27), image119, 0, 0);
  gtk_widget_set_size_request (image119, 620, 430);

  label_mbidsp = gtk_label_new (_("<span><b>Tapez l'identifiant a supprimer :</b></span>"));
  gtk_widget_show (label_mbidsp);
  gtk_fixed_put (GTK_FIXED (fixed27), label_mbidsp, 168, 8);
  gtk_widget_set_size_request (label_mbidsp, 256, 40);
  gtk_label_set_use_markup (GTK_LABEL (label_mbidsp), TRUE);

  button_mbcnfsp = gtk_button_new ();
  gtk_widget_show (button_mbcnfsp);
  gtk_fixed_put (GTK_FIXED (fixed27), button_mbcnfsp, 160, 368);
  gtk_widget_set_size_request (button_mbcnfsp, 105, 29);

  alignment79 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment79);
  gtk_container_add (GTK_CONTAINER (button_mbcnfsp), alignment79);

  hbox79 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox79);
  gtk_container_add (GTK_CONTAINER (alignment79), hbox79);

  image106 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image106);
  gtk_box_pack_start (GTK_BOX (hbox79), image106, FALSE, FALSE, 0);

  label194 = gtk_label_new_with_mnemonic (_("<span><b>confirmer</b></span>"));
  gtk_widget_show (label194);
  gtk_box_pack_start (GTK_BOX (hbox79), label194, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label194), TRUE);

  button_mbanlsp = gtk_button_new ();
  gtk_widget_show (button_mbanlsp);
  gtk_fixed_put (GTK_FIXED (fixed27), button_mbanlsp, 312, 368);
  gtk_widget_set_size_request (button_mbanlsp, 105, 29);

  alignment80 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment80);
  gtk_container_add (GTK_CONTAINER (button_mbanlsp), alignment80);

  hbox80 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox80);
  gtk_container_add (GTK_CONTAINER (alignment80), hbox80);

  image107 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image107);
  gtk_box_pack_start (GTK_BOX (hbox80), image107, FALSE, FALSE, 0);

  label195 = gtk_label_new_with_mnemonic (_("<span><b>annuler</b></span>"));
  gtk_widget_show (label195);
  gtk_box_pack_start (GTK_BOX (hbox80), label195, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label195), TRUE);

  button_qspouv = gtk_button_new ();
  gtk_widget_show (button_qspouv);
  gtk_fixed_put (GTK_FIXED (fixed27), button_qspouv, 535, 0);
  gtk_widget_set_size_request (button_qspouv, 85, 29);

  alignment92 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment92);
  gtk_container_add (GTK_CONTAINER (button_qspouv), alignment92);

  hbox92 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox92);
  gtk_container_add (GTK_CONTAINER (alignment92), hbox92);

  image120 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image120);
  gtk_box_pack_start (GTK_BOX (hbox92), image120, FALSE, FALSE, 0);

  label218 = gtk_label_new_with_mnemonic (_("<span><b>quitter</b></span>"));
  gtk_widget_show (label218);
  gtk_box_pack_start (GTK_BOX (hbox92), label218, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label218), TRUE);

  label_mbcnfsp = gtk_label_new (_("<span foreground=\"blue\" ><b>Voulez vous vraiment supprimer</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed27), label_mbcnfsp, 144, 152);
  gtk_widget_set_size_request (label_mbcnfsp, 248, 32);
  gtk_label_set_use_markup (GTK_LABEL (label_mbcnfsp), TRUE);

  radiobutton_mbnsp = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton_mbnsp);
  gtk_fixed_put (GTK_FIXED (fixed27), radiobutton_mbnsp, 184, 104);
  gtk_widget_set_size_request (radiobutton_mbnsp, 88, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_mbnsp), radiobutton_mbnsp_group);
  radiobutton_mbnsp_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_mbnsp));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton_mbnsp), TRUE);

  alignment96 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment96);
  gtk_container_add (GTK_CONTAINER (radiobutton_mbnsp), alignment96);

  hbox96 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox96);
  gtk_container_add (GTK_CONTAINER (alignment96), hbox96);

  image127 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image127);
  gtk_box_pack_start (GTK_BOX (hbox96), image127, FALSE, FALSE, 0);

  label222 = gtk_label_new_with_mnemonic (_("<span><b>Non</b></span>"));
  gtk_widget_show (label222);
  gtk_box_pack_start (GTK_BOX (hbox96), label222, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label222), TRUE);

  radiobutton_mbosp = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton_mbosp);
  gtk_fixed_put (GTK_FIXED (fixed27), radiobutton_mbosp, 304, 104);
  gtk_widget_set_size_request (radiobutton_mbosp, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_mbosp), radiobutton_mbnsp_group);
  radiobutton_mbnsp_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_mbosp));

  alignment97 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment97);
  gtk_container_add (GTK_CONTAINER (radiobutton_mbosp), alignment97);

  hbox97 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox97);
  gtk_container_add (GTK_CONTAINER (alignment97), hbox97);

  image128 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image128);
  gtk_box_pack_start (GTK_BOX (hbox97), image128, FALSE, FALSE, 0);

  label223 = gtk_label_new_with_mnemonic (_("<span><b>Oui</b></span>"));
  gtk_widget_show (label223);
  gtk_box_pack_start (GTK_BOX (hbox97), label223, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label223), TRUE);

  label_mbaltsp = gtk_label_new (_("<span foreground=\"red\" ><b>Donn\303\251e invalide !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed27), label_mbaltsp, 192, 296);
  gtk_widget_set_size_request (label_mbaltsp, 184, 32);
  gtk_label_set_use_markup (GTK_LABEL (label_mbaltsp), TRUE);

  g_signal_connect ((gpointer) button_mbcnfsp, "clicked",
                    G_CALLBACK (on_button_mbcnfsp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mbanlsp, "clicked",
                    G_CALLBACK (on_button_mbanlsp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_qspouv, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_mbnsp, "clicked",
                    G_CALLBACK (on_radiobutton_mbnsp_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_mbosp, "clicked",
                    G_CALLBACK (on_radiobutton_mbosp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (suppouv, suppouv, "suppouv");
  GLADE_HOOKUP_OBJECT (suppouv, fixed27, "fixed27");
  GLADE_HOOKUP_OBJECT (suppouv, entry_mbidsp, "entry_mbidsp");
  GLADE_HOOKUP_OBJECT (suppouv, image119, "image119");
  GLADE_HOOKUP_OBJECT (suppouv, label_mbidsp, "label_mbidsp");
  GLADE_HOOKUP_OBJECT (suppouv, button_mbcnfsp, "button_mbcnfsp");
  GLADE_HOOKUP_OBJECT (suppouv, alignment79, "alignment79");
  GLADE_HOOKUP_OBJECT (suppouv, hbox79, "hbox79");
  GLADE_HOOKUP_OBJECT (suppouv, image106, "image106");
  GLADE_HOOKUP_OBJECT (suppouv, label194, "label194");
  GLADE_HOOKUP_OBJECT (suppouv, button_mbanlsp, "button_mbanlsp");
  GLADE_HOOKUP_OBJECT (suppouv, alignment80, "alignment80");
  GLADE_HOOKUP_OBJECT (suppouv, hbox80, "hbox80");
  GLADE_HOOKUP_OBJECT (suppouv, image107, "image107");
  GLADE_HOOKUP_OBJECT (suppouv, label195, "label195");
  GLADE_HOOKUP_OBJECT (suppouv, button_qspouv, "button_qspouv");
  GLADE_HOOKUP_OBJECT (suppouv, alignment92, "alignment92");
  GLADE_HOOKUP_OBJECT (suppouv, hbox92, "hbox92");
  GLADE_HOOKUP_OBJECT (suppouv, image120, "image120");
  GLADE_HOOKUP_OBJECT (suppouv, label218, "label218");
  GLADE_HOOKUP_OBJECT (suppouv, label_mbcnfsp, "label_mbcnfsp");
  GLADE_HOOKUP_OBJECT (suppouv, radiobutton_mbnsp, "radiobutton_mbnsp");
  GLADE_HOOKUP_OBJECT (suppouv, alignment96, "alignment96");
  GLADE_HOOKUP_OBJECT (suppouv, hbox96, "hbox96");
  GLADE_HOOKUP_OBJECT (suppouv, image127, "image127");
  GLADE_HOOKUP_OBJECT (suppouv, label222, "label222");
  GLADE_HOOKUP_OBJECT (suppouv, radiobutton_mbosp, "radiobutton_mbosp");
  GLADE_HOOKUP_OBJECT (suppouv, alignment97, "alignment97");
  GLADE_HOOKUP_OBJECT (suppouv, hbox97, "hbox97");
  GLADE_HOOKUP_OBJECT (suppouv, image128, "image128");
  GLADE_HOOKUP_OBJECT (suppouv, label223, "label223");
  GLADE_HOOKUP_OBJECT (suppouv, label_mbaltsp, "label_mbaltsp");

  return suppouv;
}

GtkWidget*
create_scajouv (void)
{
  GtkWidget *scajouv;
  GtkWidget *fixed31;
  GtkWidget *image121;
  GtkWidget *button_okajouv;
  GtkWidget *alignment93;
  GtkWidget *hbox93;
  GtkWidget *image122;
  GtkWidget *label219;

  scajouv = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (scajouv, 280, 150);
  gtk_window_set_title (GTK_WINDOW (scajouv), _("ajout avec succes"));

  fixed31 = gtk_fixed_new ();
  gtk_widget_show (fixed31);
  gtk_container_add (GTK_CONTAINER (scajouv), fixed31);

  image121 = create_pixmap (scajouv, "bacgrouna.png");
  gtk_widget_show (image121);
  gtk_fixed_put (GTK_FIXED (fixed31), image121, 0, 0);
  gtk_widget_set_size_request (image121, 280, 150);

  button_okajouv = gtk_button_new ();
  gtk_widget_show (button_okajouv);
  gtk_fixed_put (GTK_FIXED (fixed31), button_okajouv, 104, 120);
  gtk_widget_set_size_request (button_okajouv, 60, 29);

  alignment93 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment93);
  gtk_container_add (GTK_CONTAINER (button_okajouv), alignment93);

  hbox93 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox93);
  gtk_container_add (GTK_CONTAINER (alignment93), hbox93);

  image122 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image122);
  gtk_box_pack_start (GTK_BOX (hbox93), image122, FALSE, FALSE, 0);

  label219 = gtk_label_new_with_mnemonic (_("<span><b>OK</b></span>"));
  gtk_widget_show (label219);
  gtk_box_pack_start (GTK_BOX (hbox93), label219, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label219), TRUE);

  g_signal_connect ((gpointer) button_okajouv, "clicked",
                    G_CALLBACK (on_button_okajouv_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (scajouv, scajouv, "scajouv");
  GLADE_HOOKUP_OBJECT (scajouv, fixed31, "fixed31");
  GLADE_HOOKUP_OBJECT (scajouv, image121, "image121");
  GLADE_HOOKUP_OBJECT (scajouv, button_okajouv, "button_okajouv");
  GLADE_HOOKUP_OBJECT (scajouv, alignment93, "alignment93");
  GLADE_HOOKUP_OBJECT (scajouv, hbox93, "hbox93");
  GLADE_HOOKUP_OBJECT (scajouv, image122, "image122");
  GLADE_HOOKUP_OBJECT (scajouv, label219, "label219");

  return scajouv;
}

GtkWidget*
create_scmdfouv (void)
{
  GtkWidget *scmdfouv;
  GtkWidget *fixed32;
  GtkWidget *image123;
  GtkWidget *button_okmdfouv;
  GtkWidget *alignment94;
  GtkWidget *hbox94;
  GtkWidget *image124;
  GtkWidget *label220;

  scmdfouv = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (scmdfouv, 280, 150);
  gtk_window_set_title (GTK_WINDOW (scmdfouv), _("modification avec succes"));

  fixed32 = gtk_fixed_new ();
  gtk_widget_show (fixed32);
  gtk_container_add (GTK_CONTAINER (scmdfouv), fixed32);

  image123 = create_pixmap (scmdfouv, "bacgrounm.png");
  gtk_widget_show (image123);
  gtk_fixed_put (GTK_FIXED (fixed32), image123, 0, 0);
  gtk_widget_set_size_request (image123, 280, 150);

  button_okmdfouv = gtk_button_new ();
  gtk_widget_show (button_okmdfouv);
  gtk_fixed_put (GTK_FIXED (fixed32), button_okmdfouv, 104, 120);
  gtk_widget_set_size_request (button_okmdfouv, 60, 29);

  alignment94 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment94);
  gtk_container_add (GTK_CONTAINER (button_okmdfouv), alignment94);

  hbox94 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox94);
  gtk_container_add (GTK_CONTAINER (alignment94), hbox94);

  image124 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image124);
  gtk_box_pack_start (GTK_BOX (hbox94), image124, FALSE, FALSE, 0);

  label220 = gtk_label_new_with_mnemonic (_("<span><b>OK</b></span>"));
  gtk_widget_show (label220);
  gtk_box_pack_start (GTK_BOX (hbox94), label220, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label220), TRUE);

  g_signal_connect ((gpointer) button_okmdfouv, "clicked",
                    G_CALLBACK (on_button_okmdfouv_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (scmdfouv, scmdfouv, "scmdfouv");
  GLADE_HOOKUP_OBJECT (scmdfouv, fixed32, "fixed32");
  GLADE_HOOKUP_OBJECT (scmdfouv, image123, "image123");
  GLADE_HOOKUP_OBJECT (scmdfouv, button_okmdfouv, "button_okmdfouv");
  GLADE_HOOKUP_OBJECT (scmdfouv, alignment94, "alignment94");
  GLADE_HOOKUP_OBJECT (scmdfouv, hbox94, "hbox94");
  GLADE_HOOKUP_OBJECT (scmdfouv, image124, "image124");
  GLADE_HOOKUP_OBJECT (scmdfouv, label220, "label220");

  return scmdfouv;
}

GtkWidget*
create_scspouv (void)
{
  GtkWidget *scspouv;
  GtkWidget *fixed33;
  GtkWidget *image125;
  GtkWidget *button_okspouv;
  GtkWidget *alignment95;
  GtkWidget *hbox95;
  GtkWidget *image126;
  GtkWidget *label221;

  scspouv = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (scspouv, 280, 150);
  gtk_window_set_title (GTK_WINDOW (scspouv), _("suppression avec succes"));

  fixed33 = gtk_fixed_new ();
  gtk_widget_show (fixed33);
  gtk_container_add (GTK_CONTAINER (scspouv), fixed33);

  image125 = create_pixmap (scspouv, "bacgrouns.png");
  gtk_widget_show (image125);
  gtk_fixed_put (GTK_FIXED (fixed33), image125, 0, 0);
  gtk_widget_set_size_request (image125, 280, 150);

  button_okspouv = gtk_button_new ();
  gtk_widget_show (button_okspouv);
  gtk_fixed_put (GTK_FIXED (fixed33), button_okspouv, 104, 120);
  gtk_widget_set_size_request (button_okspouv, 60, 29);

  alignment95 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment95);
  gtk_container_add (GTK_CONTAINER (button_okspouv), alignment95);

  hbox95 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox95);
  gtk_container_add (GTK_CONTAINER (alignment95), hbox95);

  image126 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image126);
  gtk_box_pack_start (GTK_BOX (hbox95), image126, FALSE, FALSE, 0);

  label221 = gtk_label_new_with_mnemonic (_("<span><b>OK</b></span>"));
  gtk_widget_show (label221);
  gtk_box_pack_start (GTK_BOX (hbox95), label221, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label221), TRUE);

  g_signal_connect ((gpointer) button_okspouv, "clicked",
                    G_CALLBACK (on_button_okspouv_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (scspouv, scspouv, "scspouv");
  GLADE_HOOKUP_OBJECT (scspouv, fixed33, "fixed33");
  GLADE_HOOKUP_OBJECT (scspouv, image125, "image125");
  GLADE_HOOKUP_OBJECT (scspouv, button_okspouv, "button_okspouv");
  GLADE_HOOKUP_OBJECT (scspouv, alignment95, "alignment95");
  GLADE_HOOKUP_OBJECT (scspouv, hbox95, "hbox95");
  GLADE_HOOKUP_OBJECT (scspouv, image126, "image126");
  GLADE_HOOKUP_OBJECT (scspouv, label221, "label221");

  return scspouv;
}

