/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gouv (void);
GtkWidget* create_ajtouv (void);
GtkWidget* create_mdfouv (void);
GtkWidget* create_rechouv (void);
GtkWidget* create_absouv (void);
GtkWidget* create_suppouv (void);
GtkWidget* create_scajouv (void);
GtkWidget* create_scmdfouv (void);
GtkWidget* create_scspouv (void);
